In [1]:
import numpy as np
a=np.random.rand(5)
#dont use rank one array..commit it make as row vector

In [4]:
print(a.shape)


(5,)


In [6]:
print(a.T)


[0.28539165 0.95285269 0.11825609 0.94798021 0.52738263]


In [7]:
print(np.dot(a,a.T))

2.1801600597814943


In [12]:
a=np.random.rand(5,1)

In [13]:
print(a.shape)

(5, 1)


In [10]:

print(a.T)

[[0.44955069 0.557874   0.45241176 0.282546   0.8147029 ]]


In [11]:
print(np.dot(a,a.T))

[[0.20209582 0.25079264 0.20338202 0.12701875 0.36625025]
 [0.25079264 0.3112234  0.25238876 0.15762507 0.45450156]
 [0.20338202 0.25238876 0.2046764  0.12782713 0.36858117]
 [0.12701875 0.15762507 0.12782713 0.07983224 0.23019104]
 [0.36625025 0.45450156 0.36858117 0.23019104 0.66374081]]
